# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directories:
      - "/src/azure-ai-102/genai"
      - "/src/azure-dp-100"
      - "/src/project/ai-open-webui"
      - "/src/project/ai-rag-llm"
      - "/src/project/ai-whisper"
      - "/src/project/automation-gpt"
      - "/src/project/csv"
      - "/src/project/data-science"
      - "/src/project/diagrams"
      - "/src/project/kubernetes/network-tests"
      - "/src/project/makefile-to-mprocs"
      - "/src/project/spreadsheet"
      - "/src/project/spreadsheet/google-ads-report"
      - "/src/project/spreadsheet/text-to-speech"
      - "/src/project/ytdlp-env"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "terraform"
    directories:
      - "/src/azure-ai-102/IAC"
      - "/src/azure-ai-102/genai/infra"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "terraform"
    commit-message:
      prefix: "deps"
