[project]
name = "yt-dlp-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "brotli",
  "certifi",
  "curl-cffi",
  "mutagen",
  "pycryptodome",
  "pycryptodomex",
  "requests",
  "websockets",
  "xattr",
  "yt-dlp",
  "yt-dlp-ejs",
]
