[env]
TF_VAR_subscription_id = { required = "Set Azure subscription id, for example in mise.local.toml" }

[tasks."azure:login"]
description = "Log into Azure CLI"
run = [
  'az config set core.login_experience_v2=off',
  'az login',
  'az account set --subscription "$TF_VAR_subscription_id"',
]
shell = 'bash -c'

[tasks."terraform:fmt-validate-plan"]
description = "Format and Validate Terraform files and Plan"
run = [
  'terraform -chdir=infra fmt',
  'terraform -chdir=infra validate',
  'terraform -chdir=infra plan -out=tfplan',
]

[tasks."terraform:pre-init"]
description = "Set up Azure Storage Account for Terraform Backend"
run = './infra/tf-backend-setup.sh'

[tasks."terraform:init"]
description = "Initialize Terraform"
run = ['terraform -chdir=infra init', 'terraform -chdir=infra init -upgrade']

[tasks."terraform:apply"]
description = "Apply infrastructure configuration"
run = ['terraform -chdir=infra apply tfplan']

[tasks."terraform:state"]
description = "See state file and resources"
run = ['terraform -chdir=infra state list']

[tasks."terraform:show"]
description = "See state"
run = ['terraform -chdir=infra show']

[tasks."terraform:destroy"]
description = "Destroy infrastructure"
run = ['terraform -chdir=infra destroy']
