[env]
TF_VAR_subscription_id = { required = "Set Azure subscription id, for example in mise.local.toml" }

[tasks.azlogin]
description = "Log into Azure CLI"
run = [
  'az config set core.login_experience_v2=off',
  'az login',
  'az account set --subscription "$TF_VAR_subscription_id"',
]

[tasks.tf-build]
description = "Format and Validate Terraform files and Plan"
run = [
  'cd infra',
  'terraform fmt',
  'terraform validate',
  'terraform plan -out=tfplan',
]

[tasks.tf-init]
description = "Initialize Terraform"
run = [
  'terraform init',
  'terraform init -upgrade',
]
dir = "infra"

[tasks.tf-apply]
description = "Apply infrastructure configuration"
depends = ['build']
run = [
  'terraform apply tfplan',
]
dir = "infra"

[tasks.tf-state]
description = "See state file and resources"
run = [
  'terraform state list',
]
dir = "infra"

[tasks.tf-show]
description = "See state"
run = [
  'terraform show',
]
dir = "infra"

[tasks.tf-destroy]
description = "Destroy infrastructure"
run = [
  'terraform destroy',
]
dir = "infra"
